<?php

namespace Zorbus\LinkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    public function getCategoriesWithLinks(array $ids)
    {
        $em = $this->getEntityManager();

        return $em->createQuery('
                SELECT c, l  from ZorbusLinkBundle:Category c
                JOIN c.links l
                WHERE c.id IN (:ids)
                ')
                        ->setParameter('ids', $ids)
                        ->execute();
    }

}
